type: object
required: ["homeserver", "slack_hook_port", "inbound_uri_prefix", "bot_username", "username_prefix"]
properties:
  homeserver:
    type: object
    required: ["server_name", "url"]
    properties:
      server_name:
        type: string
      url:
        type: string
  tls:
    type: object
    required: ["key_file", "crt_file"]
    properties:
      key_file:
        type: string
      crt_file:
        type: string
  slack_hook_port:
    type: integer
  inbound_uri_prefix:
    type: string
  oauth2:
    type: object
    required: ["redirect_prefix", "client_id", "client_secret"]
    properties:
      redirect_prefix:
        type: string
      client_id:
        type: string
      client_secret:
        type: string
  bot_username:
    type: string
  username_prefix:
    type: string
  matrix_admin_room:
    type: string
  enable_metrics:
    type: boolean
