type: object
required: ["homeserver", "username_prefix"]
properties:
  dbdir:
    type: string
  homeserver:
    type: object
    required: ["server_name", "url"]
    properties:
      server_name:
        type: string
      url:
        type: string
      media_url:
        type: string
      max_upload_size:
        type: number
  tls:
    type: object
    required: ["key_file", "crt_file"]
    properties:
      key_file:
        type: string
      crt_file:
        type: string
  rtm:
    type: object
    required: ["enable"]
    properties:
      enable:
        type: boolean
      log_level:
        type: "string"
        enum: ["error", "warn", "info", "debug", "off"]
  db:
    type: object
    required: ["engine", "connectionString"]
    properties:
      engine:
        type: "string"
        enum: ["postgres", "nedb"]
      connectionString:
        type: string
  slack_hook_port:
    type: integer
  inbound_uri_prefix:
    type: string
  oauth2:
    type: object
    required: ["client_id", "client_secret"]
    properties:
      client_id:
        type: string
      client_secret:
        type: string
      redirect_prefix:
        type: string
  username_prefix:
    type: string
  matrix_admin_room:
    type: string
  enable_metrics:
    type: boolean
  logging:
    type: object
    properties:
      console:
        type: "string"
        enum: ["error", "warn", "info", "debug", "off"]
      fileDatePattern:
        type: string
      timestampFormat:
        type: string
      files:
          type: "object"
          items:
              additionalProperties:
               - type: "string"
                 enum: ["error","warn","info","debug"]
